### ISSUE TITLE
Very slow on opening inspector window

### ISSUE THREAD

**Issue by furushchev** [ros-visualization/rqt_robot_monitor#10]
Opening an inspector window often slows down or sometimes causes crash of this app.
This happens especially when one aggregated message has many statuses and the pause button is NOT pressed.

**Comment by arne48** [comment]
Thank you very much for submitting this problem.
I didn't experience this issue yet. Could you please tell me, which ROS version and which Linux distribution you are using?
Also could you please give me an example of how to replicate this problem. So which node is sending how many messages per second. Because I tested this with up to 100 msg/s, which I assumed would be already ridiculously much for status messages.
