### ISSUE TITLE
Consider more coherent branch naming

### ISSUE THREAD

**Issue by norro** [ros-visualization/rqt_robot_monitor#23]
I suggest to merge `dashing-devel` either to `master` or to a `ros2` branch (depends on how you wish to handle ROS 1 vs. ROS 2 in this repo, I suppose).
Rationale: I tested the robot monitor to also be able to compile and successfully run on ROS 2 foxy (~April), so it should be fairly easy to prepare a release for foxy.

**Comment by arne48** [comment]
currently there are releases available for dashing, eloquent and foxy based on version 1.0.1.
They were pushed to rosdistro on the 13th of June and should have passed the shadow-fix stage in the meanwhile as they were listed in the "New packages for Foxy Fitzroy 2020-06-25" announcement.

About pushing dashing-devel to master. I would actually prefer a ros2 branch instead of pushing to the master branch.
At least this what I saw in several other packages and for users it would be more coherent when browsing through repositories - 
when there is a ros2[bleeding edge ros2], master[traditionally the bleeding etch of ros1] and individual release branches.
So I think we could branch dashing-devel into ros2 and publish this as the source branch for all coming ROS 2 distributions till we encounter incompatibilities. In that moment we can consider further branching.
Also using ros2[bleeding edge] for the rolling release would be nice and coherent.

I hope I could explain my point here, and it makes sense to you. :)

**Comment by norro** [comment]
Sounds very reasonable, thanks!
