### ISSUE TITLE
Resize of Robot Monitor not working

### ISSUE THREAD

**Issue by agutenkunst** [ros-visualization/rqt_robot_monitor#33]
I noticed this with foxy. 
Seems to be the only plugin with this issue.

![Peek 2020-12-05 18-57](https://user-images.githubusercontent.com/29709121/101259859-c600e180-372b-11eb-907a-802789721af7.gif)

**Comment by arne48** [comment]
Based on the topic list, it looks like no aggregator is running yet.
If so, then this is related to #31 and is fixed with 1b8a878
So you can either download the latest version of the ros2 branch, start your diagnostic_aggregator before rqt, or wait for the binary packages to be ready and added to the repository.
If this is not the cause for this issue we might have to look a bit deeper into it.

**Comment by agutenkunst** [comment]
I can confirm this is the same issue as #31 -> Close

![Peek 2020-12-16 11-08](https://user-images.githubusercontent.com/29709121/102334660-3a8b1a00-3f8f-11eb-8f32-0bf618c03a28.gif)
